### ISSUE TITLE
UiAutomator2 - Cannot read manifest information error

### ISSUE THREAD

**Issue by mano184** [appium/appium-uiautomator2-server#87]
I use windows 7 x64 installed latest node.js and npm

I synced latest appium@1.7.1

I got some hint on website to use uiautomator2 in appium to test android devices. so when I add capability uiautomator2 , it is throwing below error in script

Error:
‘An unknown server-side error occurred while processing the command. Original error: Cannot read manifest information from ‘C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.9.apk’. Does the package exist and is accessible?’

in Appium logs i see below traces:
 2017-11-07 19:58:53:703 - info: [debug] [ADB] Checking app cert for C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.9.apk.
 2017-11-07 19:58:53:912 - info: [debug] [ADB] App not signed with debug cert.
 2017-11-07 19:58:53:913 - info: [debug] [ADB] Resigning apk.
 2017-11-07 19:58:54:114 - error: [ADB] Error: Could not sign with default certificate. Original error Command ‘‘C:\Program Files\Java\jdk-9\bin\java.exe’ -jar C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\jars\sign.jar C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.9.apk --override’ exited with code 1
 at Object.wrappedLogger.errorAndThrow (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
 at ADB.callee$0$0$ (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:25:9)
 at tryCatch (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
 at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
 at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
 at GeneratorFunctionPrototype.invoke (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 at 
 at process._tickCallback (internal/process/next_tick.js:188:7)
 Error: Could not sign with default certificate. Original error Command ‘‘C:\Program Files\Java\jdk-9\bin\java.exe’ -jar C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\jars\sign.jar C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.9.apk --override’ exited with code 1
 at Object.wrappedLogger.errorAndThrow (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
 at ADB.callee$0$0$ (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:25:9)
 at tryCatch (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
 at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
 at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
 at GeneratorFunctionPrototype.invoke (C:\Users\pmaniva\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 at 
 at process._tickCallback (internal/process/next_tick.js:188:7)
 2017-11-07 19:58:54:115 - info: [debug] [UiAutomator2] Deleting UiAutomator2 session
 2017-11-07 19:58:54:115 - info: [debug] [UiAutomator2] Deleting UiAutomator2 server session
 2017-11-07 19:58:54:116 - warn: [UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id

**Comment by jags14385** [comment]
run the command with --session-override flag

**Comment by nguyenvulong** [comment]
it produced the same error after I put the --session-override flag when running appium webserver

**Comment by mano184** [comment]
Hi,
i fixed that issue. it was due to Java version. it required java 8, but i had java 9

**Comment by mano184** [comment]
closing issue. Java issue

**Comment by khandelwalgarima** [comment]
I downgraded the java version to 8 but it was still not working.
Then i uninstall appium and install appium again and that fixed the issue.
